### ISSUE TITLE
Error looking up function 'libvlc_media_thumbnail_request_by_time

### ISSUE THREAD

**Issue by Bradleykingz** [caprica/choonio#44]
I get the following error when trying to start up the project.

Error looking up function 'libvlc_media_thumbnail_request_by_time': /usr/lib/x86_64-linux-gnu/libvlc.so.5.6.0: undefined symbol: libvlc_media_thumbnail_request_by_time

Then it fails with with this stack trace:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [uk.co.caprica.vlcj.factory.MediaPlayerFactory]: Factory method 'mediaPlayerFactory' threw exception; nested exception is uk.co.caprica.vlcj.factory.NativeLibraryMappingException: Failed to properly initialise the native library
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.15.jar:5.3.15]
	... 66 common frames omitted
Caused by: uk.co.caprica.vlcj.factory.NativeLibraryMappingException: Failed to properly initialise the native library
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:184) ~[vlcj-5.0.0-20211211.173717-22.jar:na]
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:108) ~[vlcj-5.0.0-20211211.173717-22.jar:na]
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.<init>(MediaPlayerFactory.java:132) ~[vlcj-5.0.0-20211211.173717-22.jar:na]
	at uk.co.caprica.choonio.config.MediaPlayerConfig.mediaPlayerFactory(MediaPlayerConfig.java:44) ~[classes/:na]
	at uk.co.caprica.choonio.config.MediaPlayerConfig$$EnhancerBySpringCGLIB$$df18fb76.CGLIB$mediaPlayerFactory$0(<generated>) ~[classes/:na]
	at uk.co.caprica.choonio.config.MediaPlayerConfig$$EnhancerBySpringCGLIB$$df18fb76$$FastClassBySpringCGLIB$$bd8f84b2.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.15.jar:5.3.15]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.15.jar:5.3.15]
	at uk.co.caprica.choonio.config.MediaPlayerConfig$$EnhancerBySpringCGLIB$$df18fb76.mediaPlayerFactory(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.15.jar:5.3.15]
	... 67 common frames omitted
Caused by: java.lang.NoClassDefFoundError: Could not initialize class uk.co.caprica.vlcj.binding.LibVlc
	at uk.co.caprica.vlcj.support.version.LibVlcVersion.<init>(LibVlcVersion.java:49) ~[vlcj-5.0.0-20211211.173717-22.jar:na]
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.checkVersion(MediaPlayerFactory.java:195) ~[vlcj-5.0.0-20211211.173717-22.jar:na]
	at uk.co.caprica.vlcj.factory.MediaPlayerFactory.discoverNativeLibrary(MediaPlayerFactory.java:181) ~[vlcj-5.0.0-20211211.173717-22.jar:na]
	... 80 common frames omitted
```

I have vlc version 3.0.9.2 and WSL2. 

I suspect WSL might be the cause of my misfortune (since it can't run linux GUI apps) but that's just a guess.

Running `vlc -v` produces some errors:

```
VLC media player 3.0.9.2 Vetinari (revision 3.0.9.2-0-gd4c1aefe4d)
[00007fffe7ded290] main libvlc warning: cannot load module `/usr/lib/x86_64-linux-gnu/vlc/plugins/gui/libqt_plugin.so' (libQt5Core.so.5: cannot open shared object file: No such file or directory)
shared memfd open() failed: Function not implemented
[00007fffe7ebf1f0] vlcpulse audio output error: PulseAudio server connection failure: Connection refused
shared memfd open() failed: Function not implemented
[00007fffe7ecfa20] dbus interface error: Failed to connect to the D-Bus session daemon: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
[00007fffe7ecfa20] main interface error: no suitable interface module
[00007fffe7ded290] main libvlc error: interface "dbus,none" initialization failed
[00007fffe7eddb90] main interface error: no suitable interface module
[00007fffe7ded290] main libvlc error: interface "globalhotkeys,none" initialization failed
[00007fffe7ded290] main libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[00007fffe7eddb90] skins2 interface error: cannot initialize OSFactory
[00007fffe7e7ea60] main playlist: playlist is empty
[00007fffe7eddb90] [cli] lua interface: Listening on host "*console".
VLC media player 3.0.9.2 Vetinari

```

**Comment by caprica** [comment]
This project requires the latest VLC 4.x which is not yet fully released.

You either need a snapshot build or you need to build it yourself.

**Comment by caprica** [comment]
There's nothing more to be said on this issue really.
